#
# Module manifest for module 'Manage-ADShadowGroup'
#
# Generated by: lucas.cueff[a]lucas-cueff.com
#
# Generated on: 02/2017
#
 
@{
 
# Script module or binary module file associated with this manifest
ModuleToProcess = 'Manage-ADShadowGroup.psm1'
 
# Version number of this module.
ModuleVersion = '0.1'
 
# ID used to uniquely identify this module
GUID = 'a9dd94cd-102a-4b40-a27f-8fa38f0d0b35'
 
# Author of this module
Author = 'LCU'
 
# Company or vendor of this module
CompanyName = 'lucas-cueff.com'
 
# Copyright statement for this module
Copyright = '(c) 2017 lucas-cueff.com Distributed under Artistic Licence 2.0 (https://opensource.org/licenses/artistic-license-2.0).'

# Licence URI
LicenceUri = 'https://opensource.org/licenses/artistic-license-2.0'

# Repository Source Location
RepositorySourceLocation = ''

# Description of the functionality provided by this module
Description = 'Add few cmdlets to manage operations around Active Directory ShadowGroup'
 
# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = ''
 
# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''
 
# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''
 
# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = ''
 
# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = ''
 
# Processor architecture (None, X86, Amd64, IA64) required by this module
ProcessorArchitecture = ''
 
# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()
 
# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()
 
# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @()
 
# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()
 
# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()
 
# Modules to import as nested modules of the module specified in ModuleToProcess
NestedModules = @()
 
# Functions to export from this module
FunctionsToExport = '*'
 
# Cmdlets to export from this module
CmdletsToExport = '*'
 
# Variables to export from this module
VariablesToExport = '*'
 
# Aliases to export from this module
AliasesToExport = '*'
 
# List of all modules packaged with this module
ModuleList = @()
 
# List of all files packaged with this module
FileList = 'Manage-ADShadowGroup.psm1'
 
# Private data to pass to the module specified in ModuleToProcess
PrivateData = ''
 
}